[theme]
primaryColor = "#8b7355"
backgroundColor = "#f5f2ed"
secondaryBackgroundColor = "#faf8f5"
textColor = "#5d4e37"
font = "sans serif"

[server]
headless = true
enableCORS = false
port = 8501

[browser]
gatherUsageStats = false
